dist: xenial
language: node_js
sudo: false

node_js:
  - '8'

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      name: "Lint"
      script: npm run lint
      name: "Unit tests"
      script: npm run test
      name: "Unit tests with coverage report"
      script: npm run test:coverage
