version: '3'
services:
    truffle:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        command: "${ETH_CLIENT}"
        stdin_open: true
        tty: true
        volumes:
        - ./:/src
